2 try

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,16 @@
 #!/usr/bin/python3
-print("Best School")
+pyfile="$PYFILE"
+
+# Check if the environment variable $PYFILE is set
+if [ -z "$pyfile" ]; then
+    echo "Error: Environment variable \$PYFILE is not set."
+    exit 1
+fi
+
+# Check if the specified Python file exists
+if [ ! -f "$pyfile" ]; then
+    echo "Error: File '$pyfile' not found."
+    exit 1
+fi
+
+python3 "$pyfile"
